### ISSUE TITLE
error while executing make

### ISSUE THREAD

**Issue by pranithavangala** [GWW/RNASequel#1]
Im getting the following error: please advice

g++ -isystem /share/pkg/boost/1.54.0/include -isystem /usr/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/build_fragments.o src/build_fragments.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
make: **\* [src/build_fragments.o] Error 1

**Comment by GWW** [comment]
Hi,

Your compiler version is outdated RNASequel requires a version of GCC with C++11 support.

**Comment by pranithavangala** [comment]
Can you tell me how to update my compiler

Regards,
Pranitha

" An ounce of practice is worth more than a ton of preaching "

**Comment by GWW** [comment]
You need to download and install a recent version of [GCC](https://gcc.gnu.org/) or [clang](http://clang.llvm.org/) from their respective websites. Another option is to use your Linux (if you are using Linux) distributions package manager to update your compiler version.
