### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by YiChingTang** [GWW/RNASequel#2]
hi, I have an installation error on "-std=c++11" option for g++ which I think possibly could be the version issue. but my g++ version is 4.4.7 which should support the option.
any suggestions?

[root@work RNASequel]#  make
g++ -isystem /usr/include -isystem /usr/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/build_fragments.o src/build_fragments.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
make: **\* [src/build_fragments.o] Error 1

[root@Rome RNASequel]# g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)

**Comment by GWW** [comment]
Hi,

I think gcc 4.4.7 should compile fine, however, according to [Stackoverflow](http://stackoverflow.com/questions/23523634/compiling-c11-on-g-4-4-7-in-red-hat-linux), you need to use `-std=c++0x` instead of `-std=c++11`.

You can modify the flag in the Makefile on line 10.

When I get some time I will investigate way to handle this automatically.

**Comment by YiChingTang** [comment]
thanks for the quick reply. the problem solved.
And, I ran into another problem:

[root@work RNASequel]# make
g++ -isystem /opt/boost_1_58_0/include -isystem /usr/include -std=c++0x -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/build_fragments.o src/build_fragments.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /usr/include -std=c++0x -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/build_transcriptome.o src/build_transcriptome.cpp
src/build_transcriptome.cpp: In member function ‘void rnasequel::Transcriptome::process_junctions(const rnasequel::JunctionSet&, rnasequel::Strand)’:
src/build_transcriptome.cpp:47: error: expected initializer before ‘:’ token
src/build_transcriptome.cpp:55: error: expected primary-expression before ‘for’
src/build_transcriptome.cpp:55: error: expected ‘;’ before ‘for’
src/build_transcriptome.cpp:55: error: expected primary-expression before ‘for’
src/build_transcriptome.cpp:55: error: expected ‘)’ before ‘for’
make: **\* [src/build_transcriptome.o] Error 1

**Comment by GWW** [comment]
Apologies, upon further reading, it looks like [GCC 4.4.7](http://stackoverflow.com/questions/17792343/should-g-4-4-7-std-gnu0x-compile-the-for-each-construct) is also too out of date for some of the c++11 features I used in the source code. I'll figure out what version is needed and add it to the readme, in the mean time it looks like RNASequel will require at least GCC 4.6

**Comment by YiChingTang** [comment]
thanks for the suggestion.
I upgrade GCC to 4.7 and  make, can't tell where went wrong.

[root@work RNASequel]# make BOOST_ROOT=/opt/boost_1_58_0 LIBBAM_ROOT=/opt/bcbio/tools/Cellar/samtools/1.2
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/cigar.o src/cigar.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/estimate_dist.o src/estimate_dist.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/fasta_index.o src/fasta_index.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/flag.o src/flag.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/fragments.o src/fragments.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/fragment_size.o src/fragment_size.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/gtf.o src/gtf.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/index.o src/index.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/merge.o src/merge.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/models.o src/models.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/packed_seq.o src/packed_seq.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/pair_builder.o src/pair_builder.cpp
g++ -isystem /opt/boost_1_58_0/include -isystem /opt/bcbio/tools/Cellar/samtools/1.2/include -std=c++11 -Wall -Wextra -fPIC -Wstrict-aliasing -O3 -DNDEBUG -c -o src/read.o src/read.cpp
src/read.cpp: In member function ?龝oid rnasequel::BamRead::load_from_struct(const bam1_t_, const string&)??
src/read.cpp:65:38: error: ?鵈onst struct bam1_t??has no member named ?麽_aux??
src/read.cpp: In member function ?龝oid rnasequel::BamRead::load_to_struct(bam1_t_)??
src/read.cpp:86:8: error: ?鼡truct bam1_t??has no member named ?麽_aux??
src/read.cpp:90:71: error: ?鼡truct bam1_t??has no member named ?麽_aux??
make: **\* [src/read.o] Error 1

**Comment by GWW** [comment]
It looks like the new version of samtools changed their C API.

I am going to look into adding some fixes to address this (or to bundle the correct version of samtools with RNASequel source code).

In the meantime, you can download and compile an older version of samtools from [sourceforge](http://sourceforge.net/projects/samtools/files/samtools/0.1.19/).

**Comment by YiChingTang** [comment]
thanks.
I installed the 0.19 version and got some "can't find such file" problem, so I manually make some soft-link to required file like /lib/libbam.a, /include/bam/bgzf.h which looks well while retype make.
But, there's seems some issue here even using the older version of samtools.
Here's the error msg:

g++ -o src/rnasequel src/build_fragments.o src/build_transcriptome.o src/cigar.o src/estimate_dist.o src/fasta_index.o src/flag.o src/fragments.o src/fragment_size.o src/gtf.o src/index.o src/merge.o src/models.o src/packed_seq.o src/pair_builder.o src/read.o src/reader.o src/read_pair.o src/read_pairs.o src/resolve_fragments.o src/rnasequel.o src/tags.o src/transcriptome.o src/types.o src/writer.o -L/home/s991750/RNASequel/Dependencies/boost_1_58_0/lib -lboost_iostreams -lboost_program_options -lboost_system -lboost_thread -L/home/s991750/RNASequel/Dependencies/samtools-0.1.19/lib -lbam -lz -lpthread -lm  
/usr/bin/ld: cannot find -lboost_program_options
/usr/bin/ld: cannot find -lboost_system
/usr/bin/ld: cannot find -lboost_thread
collect2: error: ld returned 1 exit status
make: **\* [src/rnasequel] Error 1

btw, I found that the path to -L${BOOST_ROOT}/lib should be -L${BOOST_ROOT}/libs, and make this change to Makefile and return the same error above.
any suggestions?

**Comment by GWW** [comment]
Do your boost libraries have a different prefix? ie. are the spelt as libboost_thread.a? or do they have a different name?
